### ISSUE TITLE
Match function with and without prefix

### ISSUE THREAD

**Issue by adxl** [mattorchard/eslint-plugin-require-explicit-generics#5]
Hello, 

Thanks for this awesome plugin,

I was wondering if it was possible to match functions with a regex ? I saw in another issue where you used a wildcard, but I tried something like : `(\w+\.)?useState` for example to match `useState` and `React.useState` but it doesn't seem to work.

Are you planning to add the regex feature ? It would be really helpful because currently I have to define each hook with it's `React.*` version.

Thank you :smile:

**Comment by mattorchard** [comment]
Hi @adxl I think you should be able to specify only the un-prefixed version to get both `useState` and `React.useState` to kick out a warning/error.

In a sample eslint config I specified:
```
  rules: {
    "require-explicit-generics/require-explicit-generics": [
      "error",
      ["useState"],
    ],
  },
```
And you can see I get warnings on both ways of using the function, without needing any wildcards or duplication in my configuration.
![screenshot showing both useState and React.useState produce a warning](https://user-images.githubusercontent.com/23462213/221378167-6e42bacd-84f8-4390-9e40-4799dbd45773.png)



Let me know if this helps!
