### ISSUE TITLE
Config error: options must not have more than 0 items

### ISSUE THREAD

**Issue by rj-au** [mattorchard/eslint-plugin-require-explicit-generics#6]
No matter what I try, I always get `options must not have more than 0 items`
I'm using  ESLint@8.53.0.

The only rule that does not error is: `"require-explicit-generics/require-explicit-generics": ["error"]`

But that does not enforce any functions that should be erroring.

Am I missing something?

**Comment by mattorchard** [comment]
Howdy @richard-stafflink can you supply your eslint config?
Per the [config section of the readme](https://github.com/mattorchard/eslint-plugin-require-explicit-generics#configuration-required), the functions you want to lint must be specified.
Either as a list:
```js
rules: {
  "require-explicit-generics/require-explicit-generics": [
    "error",
    // List your functions here
    [ "myFunction", "myVar.myOtherFunction" ]
  ]
},
```
or as an object:
```js
rules: {
  "require-explicit-generics/require-explicit-generics": [
    "error",
    { "myFunction": 3, "myVar.myOtherFunction": 1 }
  ]
},
```

**Comment by rj-au** [comment]
![image](https://github.com/mattorchard/eslint-plugin-require-explicit-generics/assets/106497642/713776cb-79fb-4023-a5c6-dbfffb529324)

![image](https://github.com/mattorchard/eslint-plugin-require-explicit-generics/assets/106497642/0e001b3e-faf7-4ae7-b0b2-9d068a09e207)

**Comment by rj-au** [comment]
The whole lot:
![image](https://github.com/mattorchard/eslint-plugin-require-explicit-generics/assets/106497642/d33e1229-ac03-4185-90e5-ac441cca436a)

**Comment by mattorchard** [comment]
Ahh that is interesting, looks like VSCode is running validation of the ESLint config itself.
Seems like ESLint version `>=9` will start requiring [Options Schemas](https://eslint.org/docs/latest/extend/custom-rules#options-schemas), which are **not** defined for this library _yet_.
Maybe it is possible that VSCode's internal ESLint version is higher than the `8.53.0` of the actual code in that project.

In the coming days I'll try to Options Schemas in the hopes that repairs this issue.

In the mean time: Does this issue prevent using the library either via the ESLint command, or in terms of what errors appear in TS files? Or is it simply an editor-only warning when this file is open?

Also do you maybe have some ESLint-VSCode plugins installed that might be related?

**Comment by rj-au** [comment]
Hey Matt,
Thanks for looking into this.

The VScode extension I'm using is https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

Actually now that you mention it, it may just be an error with the VSCode extension, but running it via the ESLint CLI may be fine. I haven't tried that yet, I just assumed the VSCode extension just ran the locally installed ESLint CLI.
I'll try it out via the CLI and get back to you.

**Comment by rj-au** [comment]
> The extension uses the ESLint library installed in the opened workspace folder. If the folder doesn't provide one the extension looks for a global install version.

I have it installed in the workspace - so that answers that.

**Comment by mattorchard** [comment]
Very strange, I have the same extension (`v2.4.2`) and it doesn't cause any issue 🤔.
I will look more into it this weekend, I bet the options schema will fix it no matter what is the cause.

**Comment by mattorchard** [comment]
Howdy @richard-stafflink,
I've deployed a new version with the Options Schema 🎊.
Please try it out and let me know if it resolves the issue for you.

I deployed it as version `v1.0.0` to mark it as a breaking change in order to ensure it did not break anybody's build who was unknowingly misconfiguring the plugin.

**Comment by rj-au** [comment]
That works! thank you very much 👍️
